### ISSUE TITLE
Demo is not running because log_dir is called twice

### ISSUE THREAD

**Issue by alon1samuel** [akanazawa/hmr#105]
Hi, 

I've tried to make demo work, but I get this error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/alon/hdd/Guardian/od/hmr/demo.py", line 32, in <module>
    import src.config
  File "src/config.py", line 59, in <module>
    flags.DEFINE_string('log_dir', 'logs', 'Where to save training models')
  File "/media/alon/hdd/Guardian/od/hmr/venv_hmr/local/lib/python2.7/site-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/media/alon/hdd/Guardian/od/hmr/venv_hmr/local/lib/python2.7/site-packages/absl/flags/_defines.py", line 82, in DEFINE
    flag_values, module_name)
  File "/media/alon/hdd/Guardian/od/hmr/venv_hmr/local/lib/python2.7/site-packages/absl/flags/_defines.py", line 104, in DEFINE_flag
    fv[flag.name] = flag
  File "/media/alon/hdd/Guardian/od/hmr/venv_hmr/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from src.config.  Description from first occurrence: directory to write logfiles into
`

I've made a patch solution with commenting in src.config line number 59. 

Does anyone have another solution?

Thanks

**Comment by aoussou** [comment]
@alon1samuel 

I think it might be because you are using the latest TensorFlow version.
Try downgrading.
