### ISSUE TITLE
Demo is not working because of load error - keyword 'encoding'

### ISSUE THREAD

**Issue by alon1samuel** [akanazawa/hmr#106]
Hi, 

I've tried to make demo.py work, and had this error:

> Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/alon/hdd/Guardian/od/hmr/demo.py", line 147, in <module>
    main(config.img_path, config.json_path)
  File "/media/alon/hdd/Guardian/od/hmr/demo.py", line 121, in main
    model = RunModel(config, sess=sess)
  File "src/RunModel.py", line 56, in __init__
    self.smpl = SMPL(self.smpl_model_path, joint_type=self.joint_type)
  File "src/tf_smpl/batch_smpl.py", line 32, in __init__
    dd = pickle.load(f, encoding="latin-1") 
TypeError: load() got an unexpected keyword argument 'encoding'

I've temporarily solved the issue with commenting out the encoding in load. 

There's another solution?

Regards, Alon

**Comment by akanazawa** [comment]
This looks like python 2 vs 3 issue, please use the required packages as described in Readme.
