### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'img_path'

### ISSUE THREAD

**Issue by CocoaPebble** [akanazawa/hmr#122]
Hello, I met with some problems when I was trying to run the demo using `python -m demo --img_path data/coco1.png`. It shows like

> (hmr) inno@inno-XPS-8930:~/git/hmr$ python -m demo --img_path data/coco1.png
> Traceback (most recent call last):
>   File "/home/inno/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/home/inno/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/inno/git/hmr/demo.py", line 139, in <module>
>     config(sys.argv)
>   File "/home/inno/deep_learning_envs/hmr/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 633, in __call__
>     name, value, suggestions=suggestions)
> absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'img_path'

I am quite confused with this error and cannot find any solutions to solve this.

**Environment**:
Ubuntu 19.10
Python 2.7.17rc1
tensorflow==1.3.0 and tensorflow-gpu==1.3.0 and absl-py==0.8.1
CUDA 10.1.243

Thank you

**Comment by CocoaPebble** [comment]
I tried to upgrade to TF 1.12.0, but it has the same error. Does anyone have any ideas?
