### ISSUE TITLE
Some Bugs by Trying to run it on colab page (ImportError: dynamic module does not define init function (init_pywrap_tensorflow_internal)

### ISSUE THREAD

**Issue by soheilpaper** [akanazawa/hmr#155]
I have tried to run the [**End-to-end Recovery of Human Shape and Pose**][1] project on one [this colab page,][2] as you can see below:
So at this project there are some conflicts with the tensorflow version, and i have tried to use the `tensorflow=1.13.0` by these codes:
```
!pip2 uninstall tensorflow  -y
!pip2 install tensorflow==1.13.0rc1 --ignore-installed
%tensorflow_version 1.x
```
So by trying to run the demo coomand  (`!python2 -m demo --img_path /content/hmr/data/coco1.png`) i get some error about problem in Tensorflow module, as below :
```
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/content/hmr/demo.py", line 27, in <module>
    import tensorflow as tf
  File "/tensorflow-1.15.2/python3.7/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/tensorflow-1.15.2/python3.7/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/tensorflow-1.15.2/python3.7/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dynamic module does not define init function (init_pywrap_tensorflow_internal)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
Thanks.

  [1]: https://github.com/So-AI-love/hmr
  [2]: https://colab.research.google.com/github/soheilpaper/-tft-2.4-ili9341-STM32/blob/master/3D_pose_Estimation/Demo_MeshRCNN.ipynb

**Comment by akanazawa** [comment]
This was developed before the time of colab :). If you figure it out, happy to link the solution / your repo on README! Best of luck!

A
