### ISSUE TITLE
Cant run this with the json keypoints from Openpose

### ISSUE THREAD

**Issue by sree3333** [akanazawa/hmr#25]
2018-08-24 10:23:44.654694: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-24 10:23:44.743349: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-24 10:23:44.744012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce 920M major: 3 minor: 5 memoryClockRate(GHz): 0.954
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.57GiB
2018-08-24 10:23:44.744031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-08-24 10:23:45.020994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-24 10:23:45.021074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-08-24 10:23:45.021086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-08-24 10:23:45.021292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1345 MB memory) -> physical GPU (device: 0, name: GeForce 920M, pci bus id: 0000:01:00.0, compute capability: 3.5)
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v2.py:224: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Iteration 0
Iteration 1
Reuse is on!
Iteration 2
Reuse is on!
Restoring checkpoint /home/mirrorsize/hmr/src/../models/model.ckpt-667589..
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mirrorsize/hmr/demo.py", line 143, in <module>
    main(config.img_path, config.json_path)
  File "/home/mirrorsize/hmr/demo.py", line 123, in main
    input_img, proc_param, img = preprocess_image(img_path, json_path)
  File "/home/mirrorsize/hmr/demo.py", line 108, in preprocess_image
    scale, center = op_util.get_bbox(json_path)
  File "src/util/openpose.py", line 19, in get_bbox
    kps = read_json(json_path)
  File "src/util/openpose.py", line 13, in read_json
    kp = np.array(people['pose_keypoints']).reshape(-1, 3)
KeyError: 'pose_keypoints'

**Comment by joel-huang** [comment]
change `pose_keypoints` to `pose_keypoints_2d`.
