### ISSUE TITLE
Tensorflow 1.3.0 no longer available

### ISSUE THREAD

**Issue by muenchmark** [akanazawa/hmr#97]
Thanks for posting your code, I can't wait to start looking at it more.  I'm having trouble with the install.  When I do "pip install tensorflow==1.3.0", it comes back with an error saying the oldest version available is 1.13.1.  When I install this version I get errors running the demo when it is trying to draw the skeleton stating "name 'xrange' is undefined".  Do you know where I can get tf 1.3.0 or is there a way to run with a newer version?  Thanks!

**Comment by sandhyalaxmiK** [comment]
Fir install opendr and then tensorflow
pip install opendr==0.77
pip install tensorflow==1.3.0

**Comment by chqiwang** [comment]
what is your python version? tf1.3.0 is not available on python 3.7

**Comment by salmedina** [comment]
The main README file says it requires Python 2.7

**Comment by 2lcm** [comment]
It requires python2.7 but pickle needs python3!!!

  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/app/hmr/demo.py", line 147, in <module>
    main(config.img_path, config.json_path)
  File "/app/hmr/demo.py", line 121, in main
    model = RunModel(config, sess=sess)
  File "src/RunModel.py", line 56, in __init__
    self.smpl = SMPL(self.smpl_model_path, joint_type=self.joint_type)
  File "src/tf_smpl/batch_smpl.py", line 32, in __init__
    dd = pickle.load(f, encoding="latin-1")
TypeError: load() got an unexpected keyword argument 'encoding'

**Comment by chaowentao** [comment]
> It requires python2.7 but pickle needs python3!!!
> This does work
> dd = pickle.load(f, encoding="latin-1")
> => dd = pickle.load(f)
> 
> File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
> "**main**", fname, loader, pkg_name)
> File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
> exec code in run_globals
> File "/app/hmr/demo.py", line 147, in
> main(config.img_path, config.json_path)
> File "/app/hmr/demo.py", line 121, in main
> model = RunModel(config, sess=sess)
> File "src/RunModel.py", line 56, in **init**
> self.smpl = SMPL(self.smpl_model_path, joint_type=self.joint_type)
> File "src/tf_smpl/batch_smpl.py", line 32, in **init**
> dd = pickle.load(f, encoding="latin-1")
> TypeError: load() got an unexpected keyword argument 'encoding'
> 
> and docker is useful for tensorflow 1.3
> docker pull tensorflow/tensorflow:1.3.0-gpu

may you can delete "encoding", I try it and succeed

**Comment by jszgz** [comment]
Hello, do you know how to use mpi_inf_3dhp_to_tfrecords.py to convert mpi_inf_3dhp dataset? I failed because the code use jpg as input but the dataset I downloaded is consisting of videos. Do I need to use ffmpeg and write code to convert avi to jpg?

**Comment by mohammedhelal388** [comment]
guys i am having the same problem 
but the soltions above didnt work
i run these commands but still not working
pip install opendr==0.77
pip install tensorflow==1.3.0

when i installed the opender an error appeard like this

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kmu9k326/opendr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kmu9k326/opendr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w2fz7__8
         cwd: /tmp/pip-install-kmu9k326/opendr/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kmu9k326/opendr/setup.py", line 40
        print "Downloading %s" % osmesa_fname
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Downloading %s" % osmesa_fname)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



what i am suppose to do because i need tensorflow 1.3.0

**Comment by Ironbrotherstyle** [comment]
> 

Hello, Did you solve the problem? I followed the instruction to use python2.7, but encountered many problems when installing opendr and deepdish.
